<template>
  <div class="page">
    <div class="page-heading"><div><p class="eyebrow">Monitoring</p><h1 class="page-title">监测与数据</h1><p class="page-subtitle">把血糖、饮食和运动放在同一条时间线上，理解每一次波动。</p></div><div class="heading-actions"><el-button @click="exportCsv"><Download /> 导出数据</el-button><el-button type="primary" @click="recordDialog=true"><Plus /> 记录数据</el-button></div></div>
    <div class="alert-banner"><span><WarningFilled /></span><div><b>需要关注：晚餐后血糖连续 2 天偏高</b><p>建议今晚减少精制碳水摄入，并在餐后进行 15–20 分钟轻量活动。</p></div><button type="button" @click="router.push('/assistant')">咨询 AI</button></div>
    <section class="surface chart-card">
      <div class="chart-head"><div><p class="eyebrow">Glucose</p><h2 class="section-title">血糖趋势</h2></div><el-radio-group v-model="range" size="small" @change="load"><el-radio-button value="day">日</el-radio-button><el-radio-button value="week">周</el-radio-button><el-radio-button value="month">月</el-radio-button></el-radio-group></div>
      <div class="legend"><span><i class="target" />目标范围 3.9–7.8</span><span><i class="line" />血糖值</span><span>最近同步：刚刚</span></div>
      <div ref="chartRef" class="chart" />
      <div class="analysis"><div><b>78%</b><span>目标范围内时间 TIR</span></div><div><b>4%</b><span>低血糖占比</span></div><div><b>18%</b><span>高血糖占比</span></div><div><b>1.2</b><span>波动系数 MAGE</span></div></div>
    </section>
    <section class="records-grid">
      <article class="surface quick-card"><div class="card-title"><div><p class="eyebrow">Quick record</p><h2 class="section-title">快捷记录</h2></div></div><div class="quick-actions"><button v-for="item in quickActions" :key="item.title" type="button" @click="openRoute(item.path)"><span><component :is="item.icon" /></span><b>{{ item.title }}</b><small>{{ item.caption }}</small><ArrowRight /></button></div></article>
      <article class="surface device-card"><div class="card-title"><div><p class="eyebrow">Devices</p><h2 class="section-title">设备同步</h2></div><span class="soft-tag">2 台已连接</span></div><div class="device"><span><Watch /></span><div><b>CGM 动态血糖仪</b><small>已同步 288 条数据</small></div><em>在线</em></div><div class="device"><span><Opportunity /></span><div><b>健康手环</b><small>心率、步数与睡眠</small></div><em>在线</em></div><button class="bind" type="button" @click="router.push('/profile')">管理设备绑定</button></article>
    </section>
    <p class="ai-note">红色预警代表紧急风险。如出现意识异常、严重心悸等症状，请立即联系紧急联系人或专业医疗机构。</p>
    <el-dialog v-model="recordDialog" title="记录一项健康数据" width="420px"><p class="dialog-copy">请选择记录类型，进入对应的快速录入页。</p><div class="dialog-options"><el-button type="primary" @click="openRoute('/glucose')">血糖</el-button><el-button @click="openRoute('/diet')">饮食</el-button><el-button @click="openRoute('/exercise')">运动</el-button></div></el-dialog>
  </div>
</template>
<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import * as echarts from 'echarts'
import { ElMessage } from 'element-plus'
import { Download, Plus, WarningFilled, Food, Bicycle, TrendCharts, ArrowRight, Watch, Opportunity, Camera } from '@element-plus/icons-vue'
import { listGlucose } from '../api'
const router=useRouter(), range=ref('week'), records=ref([]), chartRef=ref(), recordDialog=ref(false); let chart
const quickActions=[{title:'手动录血糖',caption:'支持 mmol/L',icon:TrendCharts,path:'/glucose'},{title:'拍照识别饮食',caption:'AI 估算营养',icon:Camera,path:'/diet'},{title:'记录运动',caption:'时长与强度',icon:Bicycle,path:'/exercise'}]
async function load(){const days={day:1,week:7,month:30}[range.value];try{records.value=await listGlucose({from:new Date(Date.now()-days*864e5).toISOString().slice(0,19)})||[]}catch{records.value=[]}await nextTick();render()}
function render(){if(!chartRef.value)return;chart ||= echarts.init(chartRef.value);const fallback=[5.6,6.0,6.4,7.5,6.7,5.9,6.3,8.2,7.1,6.2,5.8,6.1];const vals=records.value.length?records.value.map(r=>Number(r.valueMmol)):fallback;chart.setOption({tooltip:{trigger:'axis'},grid:{left:45,right:20,top:30,bottom:35},xAxis:{type:'category',boundaryGap:false,data:vals.map((_,i)=>`${i+1}`),axisLine:{lineStyle:{color:'#dce9e4'}},axisTick:{show:false},axisLabel:{color:'#82968f'}},yAxis:{type:'value',min:2,max:12,splitLine:{lineStyle:{color:'#edf3f0'}},axisLabel:{color:'#82968f'}},series:[{type:'line',smooth:true,data:vals,symbolSize:7,itemStyle:{color:'#216b5d'},lineStyle:{color:'#35a889',width:3},areaStyle:{color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:'rgba(53,168,137,.24)'},{offset:1,color:'rgba(53,168,137,0)'}])},markArea:{silent:true,itemStyle:{color:'rgba(121,209,182,.12)'},data:[[{yAxis:3.9},{yAxis:7.8}]]},markLine:{silent:true,symbol:'none',data:[{yAxis:3.9,lineStyle:{color:'#e6a23c'}},{yAxis:7.8,lineStyle:{color:'#e35d65'}}]}}]})}
function openRoute(path){recordDialog.value=false;router.push(path)}
function exportCsv(){const rows=['时间,血糖(mmol/L)',...records.value.map(r=>`${r.measuredAt},${r.valueMmol}`)];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`health-data-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);ElMessage.success('数据已导出')}
function resize(){chart?.resize()}onMounted(()=>{load();window.addEventListener('resize',resize)});onBeforeUnmount(()=>{window.removeEventListener('resize',resize);chart?.dispose()})
</script>
<style scoped>
.heading-actions{display:flex;gap:8px}.heading-actions svg{width:16px}.alert-banner{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:14px;margin-bottom:18px;padding:15px 18px;color:#7a4b22;background:#fff8e8;border:1px solid #f0dfb0;border-radius:17px}.alert-banner>span{display:grid;width:38px;height:38px;place-items:center;background:#ffedbf;border-radius:11px}.alert-banner svg{width:19px}.alert-banner p{margin:4px 0 0;color:#936f4d;font-size:12px}.alert-banner button{padding:8px 13px;color:#7a4b22;background:white;border:1px solid #ead39b;border-radius:10px;cursor:pointer}.chart-card{padding:24px}.chart-head,.card-title{display:flex;align-items:center;justify-content:space-between}.legend{display:flex;gap:20px;margin-top:18px;color:var(--muted);font-size:11px}.legend span:last-child{margin-left:auto}.legend i{display:inline-block;width:18px;height:7px;margin-right:6px;border-radius:3px}.legend .target{background:#d8f1e8}.legend .line{height:3px;background:var(--mint-500)}.chart{height:340px}.analysis{display:grid;grid-template-columns:repeat(4,1fr);padding:17px;background:#f7faf9;border-radius:15px}.analysis div{text-align:center;border-right:1px solid var(--line)}.analysis div:last-child{border:0}.analysis b,.analysis span{display:block}.analysis b{font-size:21px}.analysis span{margin-top:5px;color:var(--muted);font-size:11px}.records-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:18px;margin:18px 0}.quick-card,.device-card{padding:23px}.quick-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-top:18px}.quick-actions button{position:relative;padding:17px;text-align:left;background:#f7faf9;border:1px solid var(--line);border-radius:15px;cursor:pointer}.quick-actions button>span{display:grid;width:38px;height:38px;place-items:center;color:var(--mint-700);background:var(--mint-100);border-radius:11px}.quick-actions svg{width:18px}.quick-actions b,.quick-actions small{display:block}.quick-actions b{margin-top:13px}.quick-actions small{margin-top:4px;color:var(--muted)}.quick-actions button>svg{position:absolute;right:13px;bottom:16px;width:14px;color:var(--muted)}.device{display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:10px;padding:14px 0;border-bottom:1px solid var(--line)}.device>span{display:grid;width:38px;height:38px;place-items:center;background:#edf7f3;border-radius:10px}.device svg{width:18px}.device b,.device small{display:block}.device small{margin-top:4px;color:var(--muted);font-size:10px}.device em{color:var(--mint-500);font-size:11px;font-style:normal}.bind{width:100%;margin-top:14px;padding:10px;color:var(--mint-700);background:white;border:1px solid var(--line);border-radius:11px;cursor:pointer}.dialog-copy{color:var(--muted)}.dialog-options{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.dialog-options .el-button{margin:0}
@media(max-width:900px){.records-grid{grid-template-columns:1fr}.quick-actions{grid-template-columns:1fr}.analysis{grid-template-columns:repeat(2,1fr);gap:14px}.analysis div{border:0}.chart{height:270px}}@media(max-width:600px){.alert-banner{grid-template-columns:38px 1fr}.alert-banner button{grid-column:2}.heading-actions{width:100%}.heading-actions .el-button{flex:1}.legend span:last-child{display:none}}
</style>
